### PR TITLE
ADD: Support for HA long-term statistics

### PR DESCRIPTION
**Pull request by koying**
Add support for the recently added long-term statistics.
Alternative to the builtin Statistics Graph Card.

Needs long-term testing and review

### CODE REVIEW

**Comment by RomRider** [comment]
Thanks, I planned to implement it but don't have time at the moment so that's helpful 😊! I'll have a look as soon as possible.

**Comment by koying** [comment]
FYI: https://github.com/home-assistant/core/issues/56052

If there is no action on the core side, it might make sense to hardcode adding 1 hour to the statistics data.
For now, the PR is acting the same as the Statistics card.

**Comment by wormiedk** [comment]
Is there any way of testing this? I would love to assist but am usure how to get it into hacs?

**Comment by aferrato** [comment]
I'm interested too, thanks.

**Comment by ondras12345** [comment]
> Is there any way of testing this?

This is what I did:
```
git clone https://github.com/koying/apexcharts-card.git apexcharts-koying
cd apexcharts-card-koying
git checkout addastatistics
npm install typescript --save-dev
npm run build
# the result is in dist/apexcharts-card.js
```
After this, you just need to copy `dist/apexcharts-card.js` to `<configuraiton directory>/www`.

**Comment by aferrato** [comment]
thank you @ondras12345, i tried, but i keep getting many typescript errors, can you post the compiled code?

**Comment by ondras12345** [comment]
This is my build: [apexcharts-card.js.txt](https://github.com/RomRider/apexcharts-card/files/7777366/apexcharts-card.js.txt)
I had to rename it to `.txt` because Github wouldn't let me upload a `.js` file.

Needless to say, you should treat this as if it was a binary (`.exe` file if you're on Windows) some random guy posted on Github. I'm in no way affiliated with this project. Use it at your own risk.

**Comment by RomRider** [comment]
> FYI: https://github.com/home-assistant/core/issues/56052
> 
> If there is no action on the core side, it might make sense to hardcode adding 1 hour to the statistics data.
> For now, the PR is acting the same as the Statistics card.

I'm going to review this over the weekend, I've seen some PR has been merged in core. Based on your comment, is there something to modify in your code to take it into account? (asking before I dive into it 😊)

**Comment by koying** [comment]
No, it's already using the "end" time that was merged recently, afaict

**Comment by batzillm** [comment]
I wanted to test it, was able to compile it and it is getting loaded by my browser but unfortunately by adding the "use_statistics: sum"-line to the config of the series, all i get is an "value.series[0] is not a ChartCardSeriesExternalConfig; value.series[0].use_statistics is extraneous" - did i miss something in the config?
I as well tried the above posted file but with the same behaviour. BrowserCache is cleaned of course.
Any ideas?

**Comment by batzillm** [comment]
> I wanted to test it, was able to compile it and it is getting loaded by my browser but unfortunately by adding the "use_statistics: sum"-line to the config of the series, all i get is an "value.series[0] is not a ChartCardSeriesExternalConfig; value.series[0].use_statistics is extraneous" - did i miss something in the config? I as well tried the above posted file but with the same behaviour. BrowserCache is cleaned of course. Any ideas?

My bad, had a typo in it.
Anyway, my old data_generator: -Graphs started giving strange graphs after switching to the new code and with my limited knwoldege of javascript i am not able to fix it. All m data_generator graphs are sometimes affected, often with different random lines and i am not able to reproduce the occurences. I will switch back to the current stable release for now. Example (random additional red lines):
grafik
Keep on the good work! The card is amazyng anyway!

**Comment by wormiedk** [comment]
Which det version should i install to test it?
I have quite a fra to choose from

**Comment by RomRider** [comment]
I'm currently working on merging this PR but it will require some more work. Wait a bit and you'll be able to test it out from a beta release.

**Comment by RomRider** [comment]
Could someone tell me how to easily get a sensor with long term statistics enabled in HA? Which integration can I use to easily generate some?

**Comment by koying** [comment]
Anything with a "measurement" state_class really, which is the default, iirc.

Bottom line: any sensor with a numeric value, afaik.

**Review by koying — COMMENTED** [review]
The statistics card is just wrong ;)
See https://github.com/home-assistant/core/issues/56052

**Comment by RomRider** [comment]
I see your point, now I understand the issue :) I'll revert !

**Comment by RomRider** [comment]
So @koying, for `lines` I'm using the `end` date to display the point, and for `column` I'll use the start date. If think that makes sense, what do you think?

**Comment by koying** [comment]
I don't use columns myself.
Assuming the left side of the column starts on the datetime tick, yes, it would make sense indeed.

Now, this would still be somewhat confusing, imo. Ideally, the column would be cantered on the datetime tick, and still use the end date, or the right side on the end date.

Maybe wishful thinking?

**Comment by RomRider** [comment]
I'll add an option with `start`, `end` and `middle`. Default will be `middle`

**Comment by RomRider** [comment]
I think this PR is now ready. I'll release and collect feedback :)

**Comment by RomRider** [comment]
Thanks @koying for bringing this in and sorry for the delay in merging :)

**Comment by AleXSR700** [comment]
Would it maybe be possible to makr `statistics` dis-/enableable?
Statistics teally make sense for larger amounts of data and little sense for recent data. So using templating it is possible to switch the source of data between normal database and long term statistics.

However, this does not work because it is not possible to dis-/enable using e.g. `statistics: []`.

Maybe it could be
```
statistics: enable
  type: max
....
```
That way the statistics settings are there when needed but it does not interrupt code functionality if type etc. are `[]`

**Comment by georgbachmann** [comment]
I have a quick question about the long-term-statistics support
I'd like to display the `mean` line as a big line, and the min/max values behind, but as an area that is above min and below max. I hacked it for now by using white as the min-color and now my chart looks like this
Bildschirm­foto 2023-01-24 um 23 15 39
So basically somewhat what i want, but instead of masking the max-chart it just overlays white which is not ideal.
Is there a proper way to archive what I want?
Also: I just discovered this card and the amount of customizability is amazing!!! Thank you very much for the whole card!

**Pull request merged**
