### PR TITLE
Add change type for statistics

### PR DESCRIPTION
**Pull request by testuser7**
Issue #552

### CODE REVIEW

**Comment by ka0n** [comment]
Please consider this pull request. Without statistics type "change", long term statistics of increasing_total stats not fully usable, e.g. for plotting daily energy consumption.

**Comment by alexdosa92** [comment]
This would be nice.

**Comment by RomRider** [comment]
Thanks

**Comment by wormuths** [comment]
I have exactly the same issue, and was wondering when we can expect the "change" function to filter down to the stable integration?  I am trying to track internet data consumption and group it by month, but without "change" support, I cannot do that.  

I love this integration, BTW.  It puts the graphs and charts in Home Assistant to shame, and I appreciate all the work that goes into developing it.

**Comment by rrozema** [comment]
As I read it, this exactly matches my wish for being able to graph changes in the data coming from sensors having a state_class: total or state_class: total_increasing. Using the existing options these show un-useful totals only.

@RomRider Is the proposed change not working correctly that it needs to remain available only in dev for 3 months? Can I do anything to help getting this feature into the release version?

**Comment by wormuths** [comment]
Yes, this is an important function, and seems to be hanging in limbo...  It would help many people if we could just graph the difference in values in the charts.

I'd *really* appreciate if this was implemented.

**Comment by jarthod** [comment]
:+1: +1 here, I see the MR is merged but not in stable yet, would appreciate this feature :)

**Comment by LambdaFlipper** [comment]
+1 here
I'm trying to visualize the year of total_increasing kWh entities grouped and currently I can only pull the change of a week without statistics!

**Pull request merged**
